server:
  port: 8080
  servlet:
    context-path: "/ho-api"
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
mybatis:
  type-aliases-package: classpath*:cn.mafangui.hotel.entity
  mapper-locations: classpath*:mybatis/mapper/*.xml

